//
// $Id: Linux_IPProtocolEndpointMetric.mof,v 1.4 2009/05/20 19:39:56 tyreld Exp $
//
// (C) Copyright IBM Corp. 2004, 2009
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Eclipse Public License from
// http://www.opensource.org/licenses/eclipse-1.0.php
//
// Author:       Heidi Neumann <heidineu@de.ibm.com>
// Contributors: 
//
// Description:
// This mof file contains the definitions for the Unix Process
// Metrics, provided by the shared library libmetricIPProtocolEndpoint.so
//



// ===================================================================
// Linux_IPProtocolEndpointMetric
// ===================================================================

[ Provider("cmpi:OSBase_MetricDefinitionProvider"),
  Description ("Class for IP ProtocolEndpoint Metric Definitions")
]
class Linux_IPProtocolEndpointMetric : CIM_BaseMetricDefinition
{
	[Experimental]
	boolean IsContinuous;
	[Experimental]
	uint16 ChangeType;
	[Experimental]
	uint16 TimeScope;
	[Experimental]
	uint16 GatheringType;
};


// ===================================================================
// Linux_IPProtocolEndpointMetricValue
// ===================================================================

[ Provider("cmpi:OSBase_MetricValueProvider"),
  Description ("Class for IP ProtocolEndpoint Metric Value")
]
class Linux_IPProtocolEndpointMetricValue : CIM_BaseMetricValue
{ };


// ===================================================================
// instance definitions
// ===================================================================

instance of Linux_MetricPlugin  
{
	MetricDefinitionClassName = "Linux_IPProtocolEndpointMetric";
 	MetricPluginName = "libmetricIPProtocolEndpoint.so";
};

instance of Linux_RepositoryPlugin  
{
	MetricDefinitionClassName = "Linux_IPProtocolEndpointMetric";
 	RepositoryPluginName = "librepositoryIPProtocolEndpoint.so";
 	CIMTranslationPluginName = "libcimplugIPProtocolEndpoint.so";
};


instance of Linux_MetricValueDefinition
{
	MetricValueClassName = "Linux_IPProtocolEndpointMetricValue";
	MetricDefinitionClassName = "Linux_IPProtocolEndpointMetric";
};
