//
// $Id: Linux_KVMMetric.mof,v 1.2 2009/05/20 19:39:56 tyreld Exp $
//
// (C) Copyright IBM Corp. 2009
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Eclipse Public License from
// http://www.opensource.org/licenses/eclipse-1.0.php
//
// Author:       Tyrel Datwyler	<tyreld@us.ibm.com>
// Contributors: 
//
// Description:
// This mof file contains the definitions for the Operating System 
// Metrics, provided by the shared library libmetricKvm.so
//



// ===================================================================
// Linux_KVMMetric
// ===================================================================

[ Provider("cmpi:OSBase_MetricDefinitionProvider"),
  Description ("Class for Operating System Metric Definitions")
]
class Linux_KVMMetric : CIM_BaseMetricDefinition
{
	[Experimental]
	boolean IsContinuous;
	[Experimental]
	uint16 ChangeType;
	[Experimental]
	uint16 TimeScope;
	[Experimental]
	uint16 GatheringType;
};


// ===================================================================
// Linux_KVMMetricValue
// ===================================================================

[ Provider("cmpi:OSBase_MetricValueProvider"),
  Description ("Class for Operating System Metric Value")
]
class Linux_KVMMetricValue : CIM_BaseMetricValue
{ };


// ===================================================================
// instance definitions
// ===================================================================

instance of Linux_MetricPlugin  
{
	MetricDefinitionClassName = "Linux_KVMMetric";
 	MetricPluginName = "libmetricKvm.so";
};

instance of Linux_RepositoryPlugin  
{
	MetricDefinitionClassName = "Linux_KVMMetric";
 	RepositoryPluginName = "librepositoryKvm.so";
 	CIMTranslationPluginName = "libcimplugKvm.so";
};


instance of Linux_MetricValueDefinition
{
	MetricValueClassName = "Linux_KVMMetricValue";
	MetricDefinitionClassName = "Linux_KVMMetric";
};
